services:
  mysql:
    image: mysql:8.0
    container_name: kasir-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: kasir_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kasir-net
    restart: always

  backend:
    build: .
    container_name: kasir-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://kasir-db:3306/kasir_db?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET}
      APP_PRINTER_NAME: POS-80
      # Tambahkan ini agar folder uploads berada di dalam container
      APP_UPLOAD_DIR: /app/uploads
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads # Mapping folder ke host server
    ports:
      - "8080:8080" # Ekspos port agar bisa di-proxy oleh Nginx/CyberPanel
    networks:
      - kasir-net
    restart: always

  frontend:
    build: ./kasir-ui
    container_name: kasir-frontend
    ports:
      - "25102:80"
    environment:
      # Variabel ini akan dibaca saat build frontend
      - VITE_API_BASE_URL=https://demokasir.dwincomputer.com
    depends_on:
      - backend
    networks:
      - kasir-net
    restart: always

volumes:
  mysql_data:

networks:
  kasir-net: